const LOCAL_DB_KEYS = {
  TOKEN: 'TOKEN'
}

const NAVIGATION_CONSTANTS = {
  LOGIN: 'LOGIN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME: 'HOME',
  DETAIL: 'DETAIL',
  DETAIL1: 'DETAIL1',
  DETAIL2: 'DETAIL2',
  DETAIL3: 'DETAIL3',
}

const REDUX_CONSTANTS = {
  SET_TOKEN: 'SET_TOKEN'
}

export {
  LOCAL_DB_KEYS,
  NAVIGATION_CONSTANTS,
  REDUX_CONSTANTS
}
