const LOCAL_DB_KEYS = {
  TOKEN: 'TOKEN'
}

const NAVIGATION_CONSTANTS = {
  LOGIN: 'LOGIN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  HOME: 'HOME',
  DETAIL: 'DETAIL',
  TOPPING:'TOPPING',
  CART:'CART',
  WELCOME: 'WELCOME',
  FOOD: 'FOOD'
}

const REDUX_CONSTANTS = {
  SET_TOKEN: 'SET_TOKEN'
}

const HEADER_MODE = {
  HOME: 'HOME',
  BACK: 'BACK'
}

const APP_ACTIONS = {
  SHOW_APP_LOADING: 'SHOW_APP_LOADING'
}

const AUTH_ACTIONS = {
  SET_AUTH_DATA: 'SET_AUTH_DATA'
}

const FOOD_ACTIONS = {
  SET_CART_DATA: 'SET_CART_DATA'
}

export {
  LOCAL_DB_KEYS,
  NAVIGATION_CONSTANTS,
  REDUX_CONSTANTS,
  HEADER_MODE,
  APP_ACTIONS,
  AUTH_ACTIONS,
  FOOD_ACTIONS
}
